default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: grapghql_game_list_test

test:
  <<: *default
  database: grapghql_game_list_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
